# Generated by Django 3.2.5 on 2021-10-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('vote', models.IntegerField(default=0)),
                ('views', models.CharField(max_length=500)),
                ('tags', models.CharField(max_length=500)),
            ],
        ),
    ]
