# Generated by Django 3.2.5 on 2021-10-07 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stackAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name': 'Data', 'verbose_name_plural': 'Datas'},
        ),
    ]
